name: Serebii Monitor

on:
  schedule:
    - cron: '0 * * * *' # 매시간 정각마다 실행
  workflow_dispatch: # 수동 실행 버튼

jobs:
  monitor:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 필수: git push 권한 허용
    steps:
      - name: 코드 가져오기
        uses: actions/checkout@v4

      - name: 파이썬 설정
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: 필요 라이브러리 설치
        run: |
          pip install beautifulsoup4 deep-translator

      - name: Serebii 스크립트 실행
        run: python check_site.py

      - name: 포켓몬 GO 스크립트 실행
        run: python check_pogo.py

      - name: 변경된 지문 저장하기
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          # 파일이 실제로 생성되었을 때만 git add 수행
          if [ -f last_hash.txt ]; then git add last_hash.txt; fi
          if [ -f pogo_last_id.txt ]; then git add pogo_last_id.txt; fi
          # 커밋할 내용이 있을 때만 커밋 및 푸시
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update hashes" && git push)
